config/routes.rb
Weblog::Application.routes.draw do
  root :to => "welcome#index"

  resources :articles
  get "about" => 'welcome#about'

end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_taggable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :tags

  def tags
    @tags = Article.tag_counts
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :tags

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params[:article])

    if @article.save
      redirect_to(@article, :notice => 'Article was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(params[:article])
      redirect_to(@article, :notice => 'Article was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to(articles_url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :tags
  def index
    @articles = Article.order('created_at desc').page(params[:page] || 1).per(10)
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActsAsTaggableOn::TagsHelper
end

class Time
  def tokyo
    self.strftime('%Y/%m/%d %H:%M:%S')
  end
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  -if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :tags
    = f.text_field :tag_list
  .actions
    = f.submit 'Save'

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing articles

%table
  %tr
    %th Title
    %th Body
    %th
    %th
    %th

  - @articles.each do |article|
    %tr
      %td= article.title
      %td= article.body
      %td= link_to 'Show', article
      %td= link_to 'Edit', edit_article_path(article)
      %td= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @article.title
%p
  %b Body:
  = @article.body
%p
  %b Tags:
  = @article.tag_list

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weblog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Weblog
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag

  %body

    %div{:class => 'container'}
      .sidebar
        %h1 BabaTatsuro.info
        %ul
          %li{'data-icon' => 'N'}= link_to "top", root_path
          %li{'data-icon' => 'i'}= link_to "about", about_path
          %li{'data-icon' => 'B'}= link_to "twitter", 'http://twitter.com/BabaTatsuro'
          %li{'data-icon' => 'U'}= link_to "facebook", 'http://facebook.com/tatsuro.baba'
        .tag_cloud
          %h2 Tag Cloud
          - tag_cloud(@tags, %w(tag1 tag2 tag3 tag4)) do |tag, css_class|
            %span{:class => css_class}= tag.name
      .content= yield

    %footer
      Copyright 2011 by Tatsuro Baba.

app/views/welcome/about.html.haml
#about
  %h2 about

  %h3 profile
  %dl
    %dt name
    %dd Tatsuro Baba

    %dt from
    %dd Tokyo, Japan

    %dt gender
    %dd male

    %dt age
    %dd 23

    %dt work
    %dd web application programmer

    %dt language
    %dd Japanese(main), English

  %h3 skills
  %dl
    %dt Ruby
    %dd 1.5 years

    %dt Ruby on Rails
    %dd 1.5 years

    %dt JavaScript (jQuery)
    %dd 1 years

    %dt= "HTML & CSS"
    %dd please see codes of this page

    %dt Database
    %dd MySQL, PostgreSQL

    %dt VCS
    %dd Git only

    %dt OS
    %dd Mac OS X for Development, Ubuntu for Server

app/views/welcome/index.html.haml
- @articles.each do |article|
  %article
    %h2.title= article.title
    .body= simple_format article.body
    .tags
      = 'Tags:'
      - article.tag_list.each do |tag|
        = tag
    .created= article.created_at.tokyo